PACKAGE_NAME="igc"
PACKAGE_VERSION="6.1-armbian-rock-5b-vendor"

BUILT_MODULE_NAME[0]="igc"

DEST_MODULE_LOCATION[0]="/kernel/drivers/net/ethernet/intel/igc"

MAKE[0]="make KDIR=/lib/modules/$(kernelver}/build"

CLEAN="make clean"

AUTOINSTALL="yes"
